name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this feature hasn't already been requested
          required: true
        - label: I have read the documentation to confirm this feature doesn't exist
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear description of the problem you're trying to solve...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear description of what you want to happen...
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: Proposed API
      description: If applicable, show how the API might look
      placeholder: |
        ```typescript
        // Example usage
        AngularSSRModule.forRoot({
          // new option here
        });
        ```

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: Other approaches you've thought about...

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important - affects my workflow
        - Critical - blocking my project
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Willingness to Contribute
      description: Would you be willing to help implement this feature?
      options:
        - label: I am willing to submit a pull request for this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information that might help us understand the request
      placeholder: Screenshots, examples from other libraries, etc.

